name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger the action only when pushing to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # This runs the action on the latest Ubuntu environment

    steps:
      # 1. Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Run a simple command directly in the workflow
      - name: Run simple command
        run: |
          echo "Hello from GitHub Actions!"
          echo "This is a simple action running directly in the workflow."
